name: Test DB Connection

on:
  push:
    branches:
      - main

jobs:
  test-db-connection:
    name: Test Database Connection
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Test the database connection by running a query
            mysql -h127.0.0.1 -uroot -p${{ secrets.DB_PASSWORD }} -P3307 -e "SELECT * FROM converter.grades;"

